api_key: "inframirror_QpHH8fZh_hvz9zWWvUAPDKQaq1GUvq7vgM6LiQkrKV8"
name: "agent-dev"
region: "Development"
datacenter: "Local DC"

backend:
  url: "http://inframirror-backend:8080"
  timeout: "10s"

instances:
  enable: true
  pingInterval: 30
  pingTimeout: 3000
  pingRetryCount: 2

  hardwareMonitoring:
    enable: true
    interval: 60 # More frequent for dev
