api_key: "inframirror_QpHH8fZh_hvz9zWWvUAPDKQaq1GUvq7vgM6LiQkrKV8"
name: "inframirror-agent"
description: "InfraMirror Agent monitoring infrastructure health and performance"
tags:
  project: "inframirror"
  ownertype: "organization"
  owner: "inframirror"
region: "US East"
datacenter: "Virginia DC1"

backend:
  url: "http://localhost:8080"
  timeout: "10s"

instances:
  enable: true
  pingInterval: 30 # seconds
  pingTimeout: 3000 # milliseconds
  pingRetryCount: 2

  hardwareMonitoring:
    enable: true
    interval: 60 # seconds (1 minute for testing)
