name: inframirror
services:
  postgresql:
    image: postgres:17.4
    container_name: postgresql
    volumes:
    - ./tmp/im/postgresql/:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=infraMirror
    - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
    - 5432:5432
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    volumes:
    - ./tmp/im/timescaledb/:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=infraMirror
    - POSTGRES_DB=telemetry
    - POSTGRES_HOST_AUTH_METHOD=trust
    - TIMESCALEDB_TELEMETRY=off
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U infraMirror -d telemetry' ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
    - 5433:5432
