# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: inframirror
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  timescaledb:
    extends:
      file: ./postgresql.yml
      service: timescaledb
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  redis:
    extends:
      file: ./redis.yml
      service: redis
