# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: inframirror
services:
  postgresql:
    image: postgres:17.4
    volumes:
    - ./tmp/im/postgresql/:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=infraMirror
    - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
    - 5432:5432
